-- Phase 2 partial implementation, 2026-10-06.
-- No DDL applied. Existing Phase 1 indexes retained.
-- Contains-search B-tree candidates rejected; additional date/sort indexes deferred.
-- See evidence/phase-2-search-listing/index-analysis.json.
